{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"Base_bot_Telegram.ipynb","provenance":[],"collapsed_sections":[],"authorship_tag":"ABX9TyONWSnTSwHV/eC1jup1spIW"},"kernelspec":{"name":"python3","display_name":"Python 3"}},"cells":[{"cell_type":"code","metadata":{"id":"JIpeNNVfypZu","colab_type":"code","colab":{}},"source":["!pip install telepot"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"LJbpxNaXtdHB","colab_type":"code","outputId":"859596fc-693a-4e3b-c017-4804d1da95a8","executionInfo":{"status":"error","timestamp":1589856349153,"user_tz":180,"elapsed":24962,"user":{"displayName":"Gorpo Orko","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GhfnUfZdNoJoquITGv0yrdth-8jV8KFkDSr_edXVdY=s64","userId":"13676609505652350042"}},"colab":{"base_uri":"https://localhost:8080/","height":1000}},"source":["import telepot\n","import subprocess\n","import time\n","\n","#api do bot\n","api = ''\n","bot = telepot.Bot(api)\n","\n","\n","# função do bot\n","def funcaoBot(msg):\n","    content_type, chat_type, chat_id = telepot.glance(msg)\n","    if msg.get('text'):\n","        texto = msg['text']\n","        #cada if é uma mensagem que o bot vai responder      \n","        if 'oi' in texto:                     \n","            bot.sendMessage(chat_id, 'Olá')\n","        if 'corno' in texto:                     \n","            bot.sendMessage(chat_id, 'Você otário')\n","        if 'python' in texto:                     \n","            bot.sendMessage(chat_id, 'É como fui programado')\n","\n","#chama a função e deixa o bot em um loop para ficar ativo   \n","bot.message_loop(funcaoBot)\n","print ('Bot esta online, para desativar o bot feche o programa!')\n","while 1:\n","        pass\n","\n","\n","\n","\n"],"execution_count":0,"outputs":[{"output_type":"stream","text":["Bot esta online, para desativar o bot feche o programa!\n"],"name":"stdout"},{"output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n","    allowed_updates=allowed_upd)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n","    return self._api_request('getUpdates', _rectify(p))\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 491, in _api_request\n","    return api.request((self._token, method, params, files), **kwargs)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 155, in request\n","    return _parse(r)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 150, in _parse\n","    raise exception.TelegramError(description, error_code, data)\n","telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n","    allowed_updates=allowed_upd)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n","    return self._api_request('getUpdates', _rectify(p))\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 491, in _api_request\n","    return api.request((self._token, method, params, files), **kwargs)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 155, in request\n","    return _parse(r)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 150, in _parse\n","    raise exception.TelegramError(description, error_code, data)\n","telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n","    allowed_updates=allowed_upd)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n","    return self._api_request('getUpdates', _rectify(p))\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 491, in _api_request\n","    return api.request((self._token, method, params, files), **kwargs)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 155, in request\n","    return _parse(r)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 150, in _parse\n","    raise exception.TelegramError(description, error_code, data)\n","telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n","    allowed_updates=allowed_upd)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n","    return self._api_request('getUpdates', _rectify(p))\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 491, in _api_request\n","    return api.request((self._token, method, params, files), **kwargs)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 155, in request\n","    return _parse(r)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 150, in _parse\n","    raise exception.TelegramError(description, error_code, data)\n","telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n","    allowed_updates=allowed_upd)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n","    return self._api_request('getUpdates', _rectify(p))\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 491, in _api_request\n","    return api.request((self._token, method, params, files), **kwargs)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 155, in request\n","    return _parse(r)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 150, in _parse\n","    raise exception.TelegramError(description, error_code, data)\n","telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n","    allowed_updates=allowed_upd)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n","    return self._api_request('getUpdates', _rectify(p))\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 491, in _api_request\n","    return api.request((self._token, method, params, files), **kwargs)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 155, in request\n","    return _parse(r)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 150, in _parse\n","    raise exception.TelegramError(description, error_code, data)\n","telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n","    allowed_updates=allowed_upd)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n","    return self._api_request('getUpdates', _rectify(p))\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 491, in _api_request\n","    return api.request((self._token, method, params, files), **kwargs)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 155, in request\n","    return _parse(r)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 150, in _parse\n","    raise exception.TelegramError(description, error_code, data)\n","telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n","    allowed_updates=allowed_upd)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n","    return self._api_request('getUpdates', _rectify(p))\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 491, in _api_request\n","    return api.request((self._token, method, params, files), **kwargs)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 155, in request\n","    return _parse(r)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 150, in _parse\n","    raise exception.TelegramError(description, error_code, data)\n","telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n","    allowed_updates=allowed_upd)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n","    return self._api_request('getUpdates', _rectify(p))\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 491, in _api_request\n","    return api.request((self._token, method, params, files), **kwargs)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 155, in request\n","    return _parse(r)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 150, in _parse\n","    raise exception.TelegramError(description, error_code, data)\n","telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n","    allowed_updates=allowed_upd)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n","    return self._api_request('getUpdates', _rectify(p))\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 491, in _api_request\n","    return api.request((self._token, method, params, files), **kwargs)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 155, in request\n","    return _parse(r)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 150, in _parse\n","    raise exception.TelegramError(description, error_code, data)\n","telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n","    allowed_updates=allowed_upd)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n","    return self._api_request('getUpdates', _rectify(p))\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 491, in _api_request\n","    return api.request((self._token, method, params, files), **kwargs)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 155, in request\n","    return _parse(r)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 150, in _parse\n","    raise exception.TelegramError(description, error_code, data)\n","telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n","    allowed_updates=allowed_upd)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n","    return self._api_request('getUpdates', _rectify(p))\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 491, in _api_request\n","    return api.request((self._token, method, params, files), **kwargs)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 155, in request\n","    return _parse(r)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 150, in _parse\n","    raise exception.TelegramError(description, error_code, data)\n","telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n","    allowed_updates=allowed_upd)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n","    return self._api_request('getUpdates', _rectify(p))\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/__init__.py\", line 491, in _api_request\n","    return api.request((self._token, method, params, files), **kwargs)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 155, in request\n","    return _parse(r)\n","  File \"/usr/local/lib/python3.6/dist-packages/telepot/api.py\", line 150, in _parse\n","    raise exception.TelegramError(description, error_code, data)\n","telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"],"name":"stderr"},{"output_type":"error","ename":"KeyboardInterrupt","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-4-0cda5480dd57>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     25\u001b[0m \u001b[0mprint\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0;34m'Bot esta online, para desativar o bot feche o programa!'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     26\u001b[0m \u001b[0;32mwhile\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 27\u001b[0;31m         \u001b[0;32mpass\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     28\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     29\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mKeyboardInterrupt\u001b[0m: "]}]}]}